language: R
cache:
  packages: true
  directories:
  - _book

addons:
  apt:
    packages:
      - libxml2-dev

script:
  - Rscript -e 'bookdown::render_book("index.rmd")'

deploy:
  skip_cleanup: true
  provider: s3
  access_key_id: AKIAITAVVAIDMYMKZOOA
  secret_access_key:
     secure: "wvUaBn8lq6BqYy8zEPgg0AMdaIipSMc0gULWc+s+XbsfsdfgUHZ1jHizqhLzuTF1uvHHQH/F44dQedPKxCeX0cl/XmDbia0fLngzc/Tne6zlbJbWKtKXUrbAJ8ilZ6iZEIPoLyXBwM6Qrh4smHKQjT1YBvPCP2cnQGsJspG2RbhVFs/w3hcckP8iHSmvIqU5GDGD/k/weQX2sUeB4dh7t45eqqtO3/78qSAGfieFr8rBKZVbKMhntzkoUxEiKnMgGb9HjhjY12WALElSEGGN8LTJ1j4TGHcRn76lAHHe6qqlfDOhsQa+RrgPTdVM5lkzCOjBgjYNR4rMwFC5kodS5m2JwfHURaZBXHCG2/yT0nikcb2juna0qUOzVxdpcBoAVsnNo8ZUTPJSuv0qSZI42IczuTscgktVz9JyYk7ncScjvhV3XhPIzY1SCgzZOKzeUZkP9RPefxAVL2H1vWcCRunamxLY8x5NLuQgBteQEPw4U8C8M1pVxE/ANoOPx5UclCkeNX2ceXGOgitdy00lOxLkrtMhcdEsmcTHb6nwMNZml4DoGBDkDoQayJO76IWvMmwpmGrHKnRl42b7ImcgKYeqzJ5hAE7rIjKD4jIVQgJwaKxkWCX2KVncOWEFZf4O+gw2OEBVI9MKZ1oJ6vXAosCrvHKOApRv1aJwnIH1i3M="
     bucket: fg2re.sellorm.com
  local-dir: _book
  region: eu-west-1
